service: psnaws-app-api

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  createProfile:
    handler: createProfile.main
    events:
      - http:
          path: profiles
          method: post
          cors: true
          authorizer: aws_iam
  getProfile:
    handler: getProfile.main
    events:
      - http:
          path: profiles/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listProfiles:
    handler: listProfiles.main
    events:
      - http:
          path: profiles/
          method: get
          cors: true
          authorizer: aws_iam          
  updateProfile:
    handler: updateProfile.main
    events:
      - http:
          path: profiles/{id}
          method: put
          cors: true
          authorizer: aws_iam
  createLink:
    handler: createLink.main
    events:
      - http:
          path: links
          method: post
          cors: true
          authorizer: aws_iam
  getLink:
    handler: getLink.main
    events:
      - http:
          path: links/{id}
          method: get
          cors: true
  confirmUser:
    handler: confirmUser.main
    events:
      - cognitoUserPool:
          pool: 'psnaws-userpool'
          trigger: 'PreSignUp'
  postConfirmUser:
    handler: postConfirmUser.main
    events:
      - cognitoUserPool:
          pool: 'psnaws-userpool'
          trigger: 'PostConfirmation'
